name: Lint, test and build on PR

on:
  pull_request:
    branches:
      - main
      - release
  push:
    branches:
      - main
      - release

jobs:
  lint_test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test:headless
      - name: Build
        run: npm run build:prod
