name: Lint, test and build

on:
  pull_request:
    branches:
      - main
      - release

  push:
    branches:
      - main
      - release

jobs:
  lint_test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:headless

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage

      - name: Build
        run: npm run build:prod
